### ISSUE TITLE
#14 Block & Inline elements

### ISSUE THREAD

**Issue by ReneKrewinkel** [Brian-Boersen/educom-html-1678179549#14]
<p>Bestudeer het overzicht "Block &amp; Inline elements". Deze module heeft verder geen opdracht. <br />Herhaal nog eens even alle tags.&nbsp;</p>

**Comment by Brian-Boersen** [comment]
block elements:
<html> <head> <body> <div> <h1>/<h6> <p> <table> <thead> <tfoot> <section> <article> <header> <footer>
<canvas> <ul> <ol> <li><hr> <nav> <pre>

inline elements:
<a> <br> <button>  <code> / <pre> <img> <picture> <input>, <textarea>, <select> <q> <script> <small>, <big> <span> <i> <b> <strong> <sub> <sup>

**Comment by Brian-Boersen** [comment]
block:


<section>, <article> <blockquote> <canvas> <div>
<header> <footer>  <form>  <h1>/<h6>
<hr> <nav>  <ol>, <ul>, <li>  <p>
<pre> <section> <table> <thead> <tfoot>

inline:

<a> <br> <button> <code>/<pre>
<img> <picture> <input>, <textarea>, <select>  <q>
<script> <small>, <big> <span>, <i>, <b>, <strong>  <sub>, <sup>
